<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Listing;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // Seeding a database is a way of creating dummy records in a table for testing purposes.
        // You can seed data directly by manually entering it here, or you can build a factory that 
        // can handle dummy data generation.

        // Manually seed data:
        // Listing::create([
        //     'title' => 'Listing One',
        //     'tags' => 'laravel, javascript',
        //     'company' => 'Some Company',
        //     'location' => 'Some Location',
        //     'email' => 'someemail@email.com',
        //     'website' => 'somewebsite.com',
        //     'description' => 'Some Description',
        // ]);
        
        // Use factories to seed data:
        User::factory(10)->create(); // -> defined in /database/factories/UserFactory.php

        Listing::factory(6)->create(); // -> defined in /database/factories/UserFactory.php
    }
}

// This file was generated by default
